[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.5",
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "faststream[kafka,rabbit]>=0.7.3",
    "passlib[bcrypt]>=1.7.4",
    "pyjwt>=2.13.0",
    "redis>=8.1.0",
    "requests>=2.34.2",
    "sqlalchemy>=2.0.51",
]
